version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-fruitdb
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: fruitdb
    ports:
      - "3308:3308"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
